// Code generated by "repacker -dst=FooConversion -src=github.com/knqyf263/repacker/example/conversion/bar.BarConversion"; DO NOT EDIT

package foo

import (
	"fmt"

	"github.com/knqyf263/repacker/example/conversion/bar"
)

// NewFooConversionFromBarBarConversion creates *FooConversion from *bar.BarConversion
func NewFooConversionFromBarBarConversion(s *bar.BarConversion) *FooConversion {
	createdAt := fmt.Sprint(s.CreatedAt)
	return &FooConversion{
		ID:        s.ID,
		Name:      s.Name,
		CreatedAt: &createdAt,
	}
}
