// Code generated by "repacker -dst=FooTag -src=github.com/knqyf263/repacker/example/tag/bar.BarTag foo/"; DO NOT EDIT

package foo

import "github.com/knqyf263/repacker/example/tag/bar"

// NewFooTagFromBarBarTag creates *FooTag from *bar.BarTag
func NewFooTagFromBarBarTag(s *bar.BarTag) *FooTag {
	return &FooTag{
		ID:   s.ID,
		Name: s.Name,
		Foo:  s.Bar,
	}
}
