// Code generated by "repacker -dst=FooSimple -src=github.com/knqyf263/repacker/example/simple/bar.BarSimple foo/"; DO NOT EDIT

package foo

import "github.com/knqyf263/repacker/example/simple/bar"

// NewFooSimpleFromBarBarSimple creates *FooSimple from *bar.BarSimple
func NewFooSimpleFromBarBarSimple(s *bar.BarSimple) *FooSimple {
	return &FooSimple{
		ID:     s.ID,
		Name:   s.Name,
		Detail: s.Detail,
	}
}
